### ISSUE TITLE
I can't run my java source code.

### ISSUE THREAD

**Issue by LimnN** [DonJayamanne/javaVSCode#78] opened 2017-09-25 16:50 UTC
here is my task.json
![2017-09-26 12 53 16](https://user-images.githubusercontent.com/14120609/30821089-a80f1b28-a256-11e7-89c3-0e99a68786e7.png)

here is my launch.json
![2017-09-26 12 54 37](https://user-images.githubusercontent.com/14120609/30821103-b827e526-a256-11e7-92a2-c86640847a6d.png)

but when I click the debug button, it just paused after a few seconds like this.and there is nothing in the debug console even hello world.
![2017-09-26 12 28 10](https://user-images.githubusercontent.com/14120609/30821117-cbc0542e-a256-11e7-8e62-9127bbd46f84.png)

then I set a breakpoint, but also nothing happened. it just like it will never get into the program.
![2017-09-26 1 00 11](https://user-images.githubusercontent.com/14120609/30821132-d9b74dbc-a256-11e7-9fdb-3d1236e424e4.png)

**Comment by LimnN** [comment] 2017-09-25 17:17
I just want a hello world in my vscode's debug console, how can I get it😂

**Comment by faustinoaq** [comment] 2017-09-25 19:59
I think this is a duplicate of #27 please take a look

**Closed as completed** 2017-09-25 19:59 UTC
Labels: duplicate
